### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [521040, 1]

### ISSUE THREAD

**Issue by sarwatfatimam** [scikit-multilearn/scikit-multilearn#118]
I have sparse labels in the data with shapes for Xtrain and yTrain as (521040, 2) and (521040, 37). I am using the following code. 

%Classifier 
clf = BinaryRelevance(classifier = LogisticRegression() , require_dense = [True, False])

%Training Classifier
clf.fit(XTrain, yTrain)

I have tried SVC() and GaussianNB() too but I get the same error.  If I remove require_dense = [True, False], the classifier works well and gives no error. 

# Error 

/usr/local/envs/py3env/lib/python3.5/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

 y = column_or_1d(y, warn=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-100-9d81eb45bc15> in <module>()
      3 
      4 # Training Classifier
----> 5 clf.fit(XTrain, yTrain)

/usr/local/envs/py3env/lib/python3.5/site-packages/skmultilearn/problem_transform/br.py in fit(self, X, y)
     69             y_subset = self.generate_data_subset(y, self.partition[i], axis=1)
     70             classifier.fit(self.ensure_input_format(
---> 71                 X), self.ensure_output_format(y_subset))
     72             self.classifiers.append(classifier)
     73 

/usr/local/envs/py3env/lib/python3.5/site-packages/sklearn/linear_model/logistic.py in fit(self, X, y, sample_weight)
   1214 
   1215         X, y = check_X_y(X, y, accept_sparse='csr', dtype=_dtype,
-> 1216                          order="C")
   1217         check_classification_targets(y)
   1218         self.classes_ = np.unique(y)

/usr/local/envs/py3env/lib/python3.5/site-packages/sklearn/utils/validation.py in check_X_y(X, y, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, warn_on_dtype, estimator)
    581         y = y.astype(np.float64)
    582 
--> 583     check_consistent_length(X, y)
    584 
    585     return X, y

/usr/local/envs/py3env/lib/python3.5/site-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    202     if len(uniques) > 1:
    203         raise ValueError("Found input variables with inconsistent numbers of"
--> 204                          " samples: %r" % [int(l) for l in lengths])
    205 
    206 

ValueError: Found input variables with inconsistent numbers of samples: [521040, 1]

**Comment by abarthakur** [comment]
The default value for `require_dense` is `[True, True]` , set here

```
    if isinstance(self.classifier, MLClassifierBase):
            self.require_dense = [False, False]
    else:
            self.require_dense = [True, True]
```

Basically, if `require_dense` is True, X ( or y) is turned into an np array, before passing to the base classifier's fit method. Otherwise, it is passed as a CSR matrix. This conversion happens in the ensure_input(or output)_format methods...
```
classifier.fit(self.ensure_input_format(X), self.ensure_output_format(y_subset))

```

Now looking at the documentation for logistic regression,

>X : {array-like, sparse matrix}, shape (n_samples, n_features)
>    Training vector, where n_samples is the number of samples and
>    n_features is the number of features.
>y : array-like, shape (n_samples,)
>    Target vector relative to X.

You can see, it doesn't take sparse matrices for y. Hence the error when you specify `require_dense=[True,False]`. Actually, `require_dense=[False,True]` would work! When you don't specify `require_dense`, it defaults to `[True, True]`, which is all good.

BONUS investigative results -

The warning and the error are related. Since you passed a CSR matrix for y, somewhere along the line (`LogisticRegression.fit -> check_X_y ->  column_or_1d`), sklearn tries to convert Y arrays of the type `(n_samples,1)` to `(n_samples,)`. 
But it isn't expecting sparse arrays at this point, so it totally mangles it by calling `np.ravel()` on it. Which converts the CSR matrix say `y` into `[y]`. Which leads to the weird error message, since length of the array becomes 1.

Maybe `sklearn.LogisticRegression` should be checking for a sparse y, and then supply a more meaningful error?

P.S. pdb is your friend :) . It didn't take me long to figure out the problem using pdb, just followed the trail up, to see what was happening to y.

**Comment by niedakh** [comment]
the problem is that scikit-learn does not, generally in all of their classifiers, allow a sparse representation of `y` :( i've even filed a bug for it years a go: https://github.com/scikit-learn/scikit-learn/issues/8908

at some point I plan to get to submititng a patch to scikit-learn to fix this, but it is a very complex endeavor there, lot's of code to play with.
