### ISSUE TITLE
Solid example codes and performance of skmultilearn

### ISSUE THREAD

**Issue by bundit786** [scikit-multilearn/scikit-multilearn#81]
Hi,
     I have begun to experiment with skmultilearn and following the guide in http://scikit.ml/api/loading.html. But I'm not sure if the document is updated or not since some code portion such as "from skmultilearn.dataset import Dataset" and 
"X_train, y_train = Dataset.load_arff_to_numpy("path_to_data/dataset-train.dump.bz2" seem to be invalid. So, can you please guide me with the solid example codes (maybe since the beginning process)? And please advise me about what and how I have to do what dump file (I already have .arff files of multi-label data).

One more question, I have noticed the comparison test between Meka and skmultilearn in https://github.com/scikit-multilearn/scikit-multilearn/tree/master/tests. All of the tests showed that the evaluation values of skmultilearn were quite different from Meka's result. Can you please describe the reason behind this issue?

Thanks and best regards,
Bundit B.

**Comment by ChristianSch** [comment]
Hi there,

regarding the loading of `arff` files please see here: https://github.com/scikit-multilearn/scikit-multilearn/issues/57 (includes an example). Please note though that it's currently broken for python 3. We are currently working on doing another release including the fix to this problem.

As for deviations of classifiers from meka/scikit-multilearn, some of them are probabilistic and hence show effects of randomness, so every run is expected to produce slightly differing results (hopefully with a low variance). Is this what you meant or am I missing your point?

I'm closing this as the bug is already taken care of in the mentioned issue. Feel free to answer though!

**Comment by bundit786** [comment]
Hi @ChristianSch,
      Thanks for the answer, regarding the arff file data loading, I have used the function 'load_from_arff()' which I think It is more understandable than 'load_dataset()' :)
       One more question, After having the overall data evaluation, how can I get into the individual label evaluation measure (acc., F-1,..)?. I tried to use 'accuracy_score(y_test[:,0], predictions[:,0])' to get the accuracy for label 0 but it didn't work.

Thanks in advance.
