### ISSUE TITLE
Error of calling RakelD using GaussianNB as a base classifier

### ISSUE THREAD

**Issue by moon412** [scikit-multilearn/scikit-multilearn#82]
Hi there,

I was trying to replicate the test of RakelD in this repo using GaussianNB as a base a classifier. I got the following error. I think it is because the fit function GaussianNB() (or MultinomialNB, LogisticRegression) only take 1-D y array. But I can use LabelPowerset to wrap GaussianNB() to make it work as shown on the documentation page (http://scikit.ml/api/classify.html).

Both RakelD and RakelO work for DecisionTreeClassifier because it can take (n_sample, n_output) y array. 

```
from sklearn.datasets import make_multilabel_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from skmultilearn.ensemble import RakelD, RakelO
import numpy as np
from sklearn.model_selection import train_test_split
from skmultilearn.problem_transform import LabelPowerset

X, y = make_multilabel_classification(sparse = True, n_labels = 5, return_indicator = 'sparse', allow_unlabeled = False)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
rakelO_temp = RakelO(GaussianNB(), model_count=10, labelset_size=2)
rakelO_temp.fit(X_train, y_train)
y_pred_temp = rakelO_temp.predict(X_test)
y_pred_temp.toarray()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-92-0ea21371832e> in <module>()
----> 1 rakelO_temp.fit(X_train, y_train)
      2 y_pred_temp = rakelO_temp.predict(X_test)
      3 y_pred_temp.toarray()

/Users/yuezha01/anaconda3/lib/python3.6/site-packages/skmultilearn/problem_transform/br.py in fit(self, X, y)
     69             y_subset = self.generate_data_subset(y, self.partition[i], axis=1)
     70             classifier.fit(self.ensure_input_format(
---> 71                 X), self.ensure_output_format(y_subset))
     72             self.classifiers.append(classifier)
     73 

/Users/yuezha01/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py in fit(self, X, y, sample_weight)
    560             Returns self.
    561         """
--> 562         X, y = check_X_y(X, y, 'csr')
    563         _, n_features = X.shape
    564 

/Users/yuezha01/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py in check_X_y(X, y, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, warn_on_dtype, estimator)
    524                         dtype=None)
    525     else:
--> 526         y = column_or_1d(y, warn=True)
    527         _assert_all_finite(y)
    528     if y_numeric and y.dtype.kind == 'O':

/Users/yuezha01/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py in column_or_1d(y, warn)
    560         return np.ravel(y)
    561 
--> 562     raise ValueError("bad input shape {0}".format(shape))
    563 
    564 

ValueError: bad input shape (67, 2)

```

**Comment by ChristianSch** [comment]
A bit of clarification: this issue is related to #87 and is caused by changes made to how label space partitioning methods work (or it was never implemented correctly?). The base classifier should be wrapped with label powerset as that's the idea of rakel.

A quick fix would be to wrap the base classifiers with `LabelPowerset` like this:
```
rakelO_temp = RakelO(LabelPowerset(GaussianNB()), model_count=10, labelset_size=2)
```
(see op's comment above for the whole code)

I raised this issue internally and will hopefully update soon as to what ought to be done. Either wrap the classifiers automatically or update the doc or issue a warning seem to be some possibilities.

**Comment by ChristianSch** [comment]
consolidating the issues #87 and #82.

---

@moon412 wrote:
I am wondering whether I should put a LabelPowerset() function to wrap the base classifier. I see both cases [here](https://github.com/scikit-multilearn/scikit-multilearn/blob/master/tests/RAkELdTesting.ipynb) with RakelD and [here](http://scikit.ml/api/classify.html) with LabelSpacePartitioningClassifier. 

As what I found earlier, RakelD, RakelO and  LabelSpacePartitioningClassifier cannot directly work with some classifiers (e.g. GaussianNB, MultinomialNB) [here](https://github.com/scikit-multilearn/scikit-multilearn/issues/82) because these base classifiers only take y with one dimension. LabelPowerset is required. 

However, I found they all directly work with DecisionTree and RandomForest because the fit and predict functions can take y with two dimensions [n_samples, n_outputs]. But I found the results are different depending on whether I put LabelPowerset around the tree classifier. 

---

@ChristianSch answered:
As per the [rakel paper](http://ieeexplore.ieee.org/document/5567103/):
> A less common problem transformation method considers each different sub-
set of L as a single label. It so learns one single-label classifier
h:X → P(L), where P(L) is the powerset of L, containing all possible label subsets. We will
refer to this method as **Label Powerset (LP) learning**. LP has the advantage of
taking label correlations into account, but suffers from the large number of label
subsets, the majority of which are associated with very few examples.
**This paper proposes an approach that constructs an ensemble of LP classi-
fiers. Each LP classifier is trained using a different small random subset of the
set of labels.** The proposed approach, dubbed RAKEL (RAndom k-labELsets),
aims at taking into account label correlations and at the same time avoiding
the aforementioned problems of LP. Ensemble combination is accomplished by
thresholding the average zero-one decisions of each model per considered la-
bel. The paper investigates the issue of selecting appropriate parameters (subset
size, number of models, threshold) for RAKEL through an experimental study
on three domains concerning protein, image and document classification. Results
of performance comparison against the BR and LP methods are in favor of the
proposed approach.

A while ago the classifiers that work on label subspaces, such as rakel and others, where changed to a unified approach via ` LabelSpacePartitioningClassifier`, as far as I can see. I don't know about using it directly, but you're using it whilst using rakel-o/rakel-d.
I had a quick glance at the code and it seems the `LabelPowerset`, which ought to be part of rakel, was lost or deliberately cleared to allow more freedom. So from my understanding the rakel classifiers ought to be used with `LabelPowerset(BaseClassifier())`.

**Comment by ChristianSch** [comment]
As a follow up:  #78 should be looked at when we determined a solution and see if there's anything we need to check or if this is behavior that's expected.

**Comment by moon412** [comment]
Hi @ChristianSch , thanks for all the detailed replies. They make a lot of sense to me. The skmultilearn module is super helpful for me to implement multi-label classification methods on label space. I am just hoping that the implementation examples could be updated and consistent if there is a chance.

BTW, I just found that DecisionTree and RandomForest can also work with multi-output problem [here](http://scikit-learn.org/stable/modules/tree.html#multi-output-problems). But it is different to use LabelPowerset(DecisionTreeClassifier()) and DecisionTreeClassifier) to fit multi-label data.

**Comment by niedakh** [comment]
ok, so some clarification from my side, having wrote code. I did choose to allow non-LP classifiers to be used with rakel approach, as it may be useful to have randomized overlapping chains trained like this. I am transforming this approach now, we will have a separate overlapping classifier, with a random clusterer, and a RakelO as a separate subclass.

**Comment by niedakh** [comment]
I fixed this in master now, RakelD takes only a base classifier, as label powerset is set by default, a partition classifier should be used if a different base clasifier is desired. thank you for your feedback!
